#!/bin/bash

# Run the command and capture its output
output=$(oc get svc)

# Initialize ingress YAML file with API version and kind
echo "apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:" > ingress.yaml

# Loop through the output and add each service as a path to the ingress YAML file
while read -r line; do
  # Skip the header and any lines that are not services
  if [[ $line == NAME* || $line == *NodePort* ]]; then
    continue
  fi
  
  # Extract the service name and ClusterIP port
  service_name=$(echo $line | awk '{print $1}')
  cluster_ip_port=$(echo $line | awk '{print $3}')
  
  # Add the service as a path to the ingress YAML file
  echo "  - path: /$service_name
    backend:
      serviceName: $service_name
      servicePort: $cluster_ip_port" >> ingress.yaml
done <<< "$output"

for service_name in $a; do
  # Extract the ClusterIP port for the current service
  cluster_ip_port=$(echo "$b" | sed -n ${i}p)
  
  # Add the service as a path to the ingress YAML file
  echo "  - path: /$service_name
    backend:
      serviceName: $service_name
      servicePort: $cluster_ip_port"
# Define the two lists of values
my_list="a b c d e f g h"
your_list="i j k l m n o p"

# Loop through the lists and print a message using one value from each list
for i in $(seq 1 $(echo $my_list | wc -w)); do
  my_value=$(echo $my_list | awk "{print \$$i}")
  your_value=$(echo $your_list | awk "{print \$$i}")
  echo "This is server $my_value$your_value"
done
