#!/bin/bash

CONFIGMAP_NAME=my-configmap
GRAFANA_POD_NAME=my-grafana-pod

echo "Watching for changes to ConfigMap $CONFIGMAP_NAME"

while true; do
  # Check if the ConfigMap has been modified
  kubectl get configmap $CONFIGMAP_NAME -o json | jq -e '.metadata.annotations."kubectl.kubernetes.io/last-applied-configuration"' >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "ConfigMap $CONFIGMAP_NAME has changed. Reloading $GRAFANA_POD_NAME..."
    kubectl delete pod $GRAFANA_POD_NAME
  fi

  # Wait for 10 seconds before checking again
  sleep 10
done
